export class Constants {
  /**
   * Surface width in xComponent.
   */
  static readonly X_COMPONENT_SURFACE_WIDTH = 1920;

  /**
   * Surface height in xComponent.
   */
  static readonly X_COMPONENT_SURFACE_HEIGHT = 1080;

  /**
   * Border width in xComponent.
   */
  static readonly X_COMPONENT_BORDER_WIDTH = 0.5;

  /**
   * Border width in capture button.
   */
  static readonly CAPTURE_BUTTON_BORDER_WIDTH = 3;

  /**
   * Border radius size in capture button.
   */
  static readonly CAPTURE_BUTTON_BORDER_RADIUS = 70;

  /**
   * Margins of the component.
   */
  static readonly CAPTURE_BUTTON_COLUMN_MARGIN = 24;

  /**
   * Paddings of the component.
   */
  static readonly CAPTURE_BUTTON_COLUMN_PADDING = 24;

  /**
   * Size of the back icon.
   */
  static readonly BACK_ICON_SIZE = 24;

  /**
   * Size of the back icon.
   */
  static readonly IMAGE_SIZE = 25;

  /**
   * Margins of the back icon.
   */
  static readonly BACK_ICON_MARGIN = 24;

  /**
   * The full percentage of component.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * The Eighty-five percent of component.
   */
  static readonly EIGHTY_FIVE_PERCENT: string = '85%';

  /**
   * The Eighty percent of component.
   */
  static readonly EIGHTY_PERCENT: string = '80%';

  /**
   * The seventy-five percent of the components.
   */
  static readonly SEVENTY_FIVE_PERCENT: string = '75%';


  /**
   * The seventy percent of the components.
   */
  static readonly SEVENTY_PERCENT: string = '70%';

  /**
   * The forty percent of the components.
   */
  static readonly FORTY_PERCENT: string = '40%';

  /**
   * The thirty percent of the components.
   */
  static readonly THIRTY_PERCENT: string = '30%';

  /**
   * The fifteen percent of the bottom of the margin.
   */
  static readonly FIFTEEN_PERCENT: string = '15%';

  /**
   * The ten percent of the bottom of the margin.
   */
  static readonly TEN_PERCENT: string = '10%';

  /**
   * The zero percent of the bottom of the margin.
   */
  static readonly ZERO_PERCENT: string = '0%';

  /**
   * border radius.
   */
  static readonly TEXT_BORDER_RADIUS: number = 25;

  /**
   * font size.
   */
  static readonly FONT_SIZE_14: number = 14;

  /**
   * column space.
   */
  static readonly COLUMN_SPACE_24: number = 24;

  /**
   * row space.
   */
  static readonly ROW_SPACE_24: number = 24;

  /**
   * default zoom ratio.
   */
  static readonly DEFAULT_ZOOM_RATIO: number = 1;

  /**
   * border radius.
   */
  static readonly BORDER_RADIUS_14: number = 14;

  /**
   * default zoom radio min.
   */
  static readonly ZOOM_RADIO_MIN: number = 1;

  /**
   * default zoom radio max.
   */
  static readonly ZOOM_RADIO_MAX: number = 6;

  /**
   * default zoom radio step.
   */
  static readonly ZOOM_RADIO_MAX_STEP: number = 0.1;

  /**
   * default zoom radio step.
   */
  static readonly ZOOM_RADIO_MIN_STEP: number = 0.01;

  /**
   * capture Column width.
   */
  static readonly CAPTURE_COLUMN_WIDTH: number = 50;

  /**
   * capture Column width.
   */
  static readonly CAPTURE_ROW_HEIGHT: number = 28;

  /**
   * AUDIO_BITRATE.
   */
  static readonly AUDIO_BITRATE: number = 48000;

  /**
   * AUDIO_CHANNELS.
   */
  static readonly AUDIO_CHANNELS: number = 2;

  /**
   * AUDIO_SAMPLE_RATE.
   */
  static readonly AUDIO_SAMPLE_RATE: number = 48000;

  /**
   * VIDEO_BITRATE.
   */
  static readonly VIDEO_BITRATE: number = 512000;

  /**
   * VIDEO_FRAME.
   */
  static readonly MAX_VIDEO_FRAME: number = 60;

  /**
   * FLASH_POSITION_X.
   */
  static readonly FLASH_POSITION_X: number = 0;

  /**
   * FLASH_POSITION_Y.
   */
  static readonly FLASH_POSITION_Y: number = 50;

  /**
   * Index content width.
   */
  static readonly INDEX_CONTENT_WIDTH: string = '91.1%';
  /**
   * Index divider height.
   */
  static readonly DIVIDER_HEIGHT: number = 0.5;
  /**
   * Index divider width.
   */
  static readonly DIVIDER_WIDTH: string = '93%';
  /**
   * Drawer divider width.
   */
  static readonly DIVIDER_DRAWER_WIDTH: string = '90%';
  /**
   * Card title height.
   */
  static readonly CARD_TITLE_HEIGHT: number = 20;
  /**
   * Card text height.
   */
  static readonly CARD_TEXT_HEIGHT: number = 48;
  /**
   * Index title height.
   */
  static readonly INDEX_TITLE_HEIGHT: number = 112;
  /**
   * Full screen width.
   */
  static readonly FULL_WIDTH: string = '100%';
  /**
   * Full screen height.
   */
  static readonly FULL_HEIGHT: string = '100%';
  /**
   * Font size of unchecked title.
   */
  static readonly FONT_SIZE_UNCHECKED = 18;
  /**
   * Font size of checked title.
   */
  static readonly FONT_SIZE_CHECKED: number = 24;
  /**
   * Content height.
   */
  static readonly CONTENT_HEIGHT: number = 300;
  /**
   * List height.
   */
  static readonly LIST_HEIGHT: number = 48;
  /**
   * List card width.
   */
  static readonly LIST_CARD_WIDTH: number = 272;
  /**
   * List card height.
   */
  static readonly LIST_CARD_HEIGHT: number = 344;
  /**
   * List content height.
   */
  static readonly LIST_CONTENT_HEIGHT: string = '110%';
  /**
   * Background tab height.
   */
  static readonly BACKGROUND_TAB_HEIGHT: number = 40;
  /**
   * Index button height.
   */
  static readonly INDEX_BUTTON_HEIGHT: number = 60;
  /**
   * Background tab width.
   */
  static readonly BACKGROUND_TAB_WIDTH: number = 96;
  /**
   * Drawer width.
   */
  static readonly DRAWER_WIDTH: number = 264;
  /**
   * Sub tab width.
   */
  static readonly SUB_TAB_WIDTH: number = 56;
  /**
   * Sub slide width.
   */
  static readonly SUB_SLIDE_TAB_WIDTH: number = 56;
  /**
   * Sub tab bottom height.
   */
  static readonly SUB_TAB_BOT_HEIGHT: number = 25;
  /**
   * Sub tab width.
   */
  static readonly SUB_TAB_HEIGHT: number = 30;
  /**
   * Sub list width.
   */
  static readonly SUB_LIST_WIDTH: string = '85%';
  /**
   * Side tab width.
   */
  static readonly SIDE_TAB_WIDTH: string = '27.8%';
  /**
   * Side contend width.
   */
  static readonly SIDE_CONTEND_WIDTH: string = '72.2%';
  /**
   * Tab index0.
   */
  static readonly TAB_INDEX_ZERO: number = 0;
  /**
   * Tab index1.
   */
  static readonly TAB_INDEX_ONE: number = 1;
  /**
   * Tab index2.
   */
  static readonly TAB_INDEX_TWO: number = 2;
  /**
   * Tab index3.
   */
  static readonly TAB_INDEX_THREE: number = 3;
  /**
   * Tab index4.
   */
  static readonly TAB_INDEX_FOUR: number = 4;
  /**
   * Tab index5.
   */
  static readonly TAB_INDEX_FIVE: number = 5;
  /**
   * Image tab size.
   */
  static readonly IMAGE_SIZE_TAB: number = 22;
  /**
   * Image middle size.
   */
  static readonly IMAGE_SIZE_MIDDLE: number = 56;
  /**
   * More image width.
   */
  static readonly MORE_IMAGE_WIDTH: number = 20;
  /**
   * More image height.
   */
  static readonly MORE_IMAGE_HEIGHT: number = 15;
  /**
   * Drawer image height or width.
   */
  static readonly DRAWER_IMAGE_HEIGHT_WIDTH: number = 24;
  /**
   * List image height or width.
   */
  static readonly LIST_IMAGE_HEIGHT_WIDTH: number = 40;
  /**
   * Image offset.
   */
  static readonly IMAGE_OFFSET: number = -15;
  /**
   * Icon offset.
   */
  static readonly ICON_Offset: number = -3;
  /**
   * Animation duration.
   */
  static readonly ANIMATION_DURATION: number = 300;
  /**
   * Margin sixteen.
   */
  static readonly MARGIN_SIXTEEN: number = 16;
  /**
   * Margin button top.
   */
  static readonly MARGIN_BUTTON_TOP: number = 48;
  /**
   * Translate top.
   */
  static readonly TRANSLATE_TOP: number = -40;
  /**
   * Translate bottom.
   */
  static readonly TRANSLATE_BOTTOM: number = 40;
  /**
   * Border radius drawer.
   */
  static readonly BORDER_RADIUS_DRAWER: number = 16;
  /**
   * Border radius index list.
   */
  static readonly BORDER_RADIUS_INDEX_LIST: number = 18;
  /**
   * Border radius drawer content.
   */
  static readonly BORDER_RADIUS_DRAWER_CONTENT: number = 20;
  /**
   * Border radius back tab.
   */
  static readonly BORDER_RADIUS_BACK_TAB: number = 21;
  /**
   * Divider strokeWidth.
   */
  static readonly STROKE_WIDTH: number = 2;
  /**
   * Slice index index0.
   */
  static readonly SLICE_INDEX_ZERO: number = 0;
  /**
   * Slice index index6.
   */
  static readonly SLICE_INDEX_SIX: number = 6;
  /**
   * fontWeight.
   */
  static readonly FONT_WEIGHT_TAB: number = 600;
};